# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QPixmap
import os,cv2,glob,random
from PIL import Image
import PIL
import glob
import imutils

filevideo = ''
foldername = ''

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1065, 834)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_edit1 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit1.setGeometry(QtCore.QRect(200, 100, 501, 31))
        self.line_edit1.setObjectName("line_edit1")
        
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(90, 100, 91, 21))
        self.label1.setObjectName("label1")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(740, 100, 111, 31))
        self.button1.setObjectName("button1")
        self.button1.clicked.connect(self.clicker1)


        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(740, 210, 111, 31))
        self.button2.setObjectName("button2")

        self.button2.clicked.connect(self.clicker2)


        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(100, 210, 91, 21))
        self.label2.setObjectName("label2")
        self.line_edit2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit2.setGeometry(QtCore.QRect(200, 210, 501, 31))
        self.line_edit2.setObjectName("line_edit2")
        self.button3 = QtWidgets.QPushButton(self.centralwidget)
        self.button3.setGeometry(QtCore.QRect(380, 290, 101, 31))
        self.button3.setObjectName("button3")
        self.button3.clicked.connect(self.exporter)
        self.converting_label = QtWidgets.QLabel(self.centralwidget)
        self.converting_label.setGeometry(QtCore.QRect(270, 290, 81, 20))
        self.converting_label.setText("")
        self.converting_label.setObjectName("converting_label")
        self.graphicsView = QtWidgets.QLabel(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(180, 390, 511, 341))
        self.graphicsView.setObjectName("graphicsView")
        self.nextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.nextbutton.setGeometry(QtCore.QRect(740, 690, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nextbutton.setFont(font)
        self.nextbutton.setObjectName("nextbutton")
        self.nextbutton.clicked.connect(self.display)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1065, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Extractor"))
        self.label1.setText(_translate("MainWindow", "File Name : "))
        self.button1.setText(_translate("MainWindow", "Browse"))
        self.button2.setText(_translate("MainWindow", "Browse"))
        self.label2.setText(_translate("MainWindow", "Save To : "))
        self.button3.setText(_translate("MainWindow", "Extract"))
        self.nextbutton.setText(_translate("MainWindow", "Next  "))
    def clicker1(self):
        fname = QFileDialog.getOpenFileName()
        if fname:
            self.line_edit1.setText(str(fname[0]))
            global filevideo
            filevideo = str(fname[0])
            print(filevideo)


    def clicker2(self):
        foname = QFileDialog.getExistingDirectory()
        if foname:
            self.line_edit2.setText(foname)
            global foldername
            foldername = foname

    def exporter(self):
        self.button3.setEnabled(False)
        capture = cv2.VideoCapture(filevideo)
        try:
            os.chdir(foldername)
            if not os.path.exists('Data'):
                os.makedirs('Data')
        except OSError:
            print("Error in creating the file")
        counter = 1

        while True:
            ret,frame = capture.read()
            if ret:
                re_frame = imutils.resize(frame,width=500)
                name = f"{foldername}/data/frame{counter}.jpg"
                print(name)
                cv2.imwrite(name,re_frame)
                counter += 1
            else:
                break

        capture.release()
        cv2.destroyAllWindows()
        self.converting_label.setText("Completed!")
        self.display()


    def display(self):
        img_dir = glob.glob("Data/*.jpg")
        pix = QPixmap(random.choice(img_dir))
        self.graphicsView.setPixmap(pix)





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
